baseURL = "http://example.org/"
languageCode = "en-us"

title = "Levelup Productivity"
theme = "hugo-theme-learn"
author = "Edwin Muraya"
description = "From basic to Advanced"

copyright = "©{year}, All Rights Reserved" 
showPoweredBy = false 
# For search functionality
[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"

  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Documentation for Hugo Learn Theme"
  author = "Eduuh Muraya"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"


